= Version Handling for Large Projects
:sectnums:
:toc:

== Initial Situation

=== Internal Project Dependencies
- Frequent changes on patch or minor level for released versions
- The trunks of different projects are using integration releases
- Update is maintained manually
- Small number of projects ( < 20 )

=== External Project Dependencies
- More than 100 dependencies in the platform project
- Other projects have 25, 11 or none different dependencies.
- Conflicts between internal projects are possible.
- Updates are difficult, because there are a lot of transitive dependencies that may cause conflicts.

== Requirements
=== Product or Internal Project Dependencies
- Updates of internal should be maintained automatically.
* Based on a branch of the main product the version of the dependencies should be updated automatically and tested
* The update must consider the used version of the branch. This ensures that the main version always remains stable.
* The order of versions must be handled correctly.
* Support of Subversion and Git is mandatory.

.order of the ivy resolver for `1.0.+`
----
    1.0.1 -> 1.0.1-rc.1 -> 1.0.1-rc.2
        latest:   1.0.1-rc.2  (1-rc.2 > 1)
----

.correct order of semantic versions
----
    1.0.1-rc.1 -> 1.0.1-rc.2 -> 1.0.1
        latest: 1.0.1
----

- A developer must be able to override these versions easily and reproducibly with a local version.
** This configuration must be handled in a separate file.
** The file *must not* be stored in the VCS. Furthermore, it must be possible to create a configuration in the VCS to prevent the storage at all.
** The handling should be supported by some helper tasks.
- It must be possible to specify a version of a component or a version of a filter configuration.
- The configuration of internal dependencies has to be configured in a separated file.

=== Standards Filter Formats
- bom
- pom
- ivy
- properties

=== External Library Dependencies
- All external dependencies should be maintained in one single configuration.
** This dependency management configuration should be handled like any other internal project.
** The result of this project should be published via a Maven or an Ivy project.
** Other projects should use the dependency management configuration like a filter for versions.
** The update of this dependencies should be maintained manually, but supported by some helper tasks.
** It must be possible to control the update process.
*** Updates for all dependencies should be done on the same level (major, minor, patch).
*** Conflicts must be logged.
*** A conflict resolution must be configurable.
- Versions of some libraries do not follow semantic versioning. Nonetheless it must be possible to specify an update rule also for these special dependencies.
- The dependency management configuration must be deliverable to all customers.
** In a customer project, this configuration must also be overwritten.
** It should be possible to use other configurations for filtering dependencies with a version.
-  Updates should be pulled only from configured repositories.

=== Questions and Answers - Issues and Discussion
- What should happen if a dependency with a correct version is specified?

. This version is used
.. without any messages.
.. but a warning is printed out.
. If the dependency is listed in the dependency filter the version is not used and
.. an error is thrown.
.. the version is taken from the filter configuration.
. In case of a transitiv dependency downstream from a configured dependency with a version that does not match - an error is thrown.

Since all use cases are conceivable options, each should be configurable.

- Which format should be used for lock files and configuration files?

I think JSON format is readable and easy to use.

== Workflow - Automatic Updates for Internal Dependencies
.  Triggered by new available release versions (check repository for changes)
.. https://marketplace.atlassian.com/plugins/com.entertainment.bamboo.plugins.httpclient/server/overview
.. https://marketplace.atlassian.com/plugins/fr.armotic.bamboo.plugins.filedownloader/server/overview
.. https://marketplace.atlassian.com/plugins/org.gaptap.bamboo.maven.maven-artifact-download-plugin/server/overview
.. Implement own plugin for Bamboo.
. Commit changes to VCS, because the change must be used and the build takes more time.
. An automatic build is triggered due to the change in the VCS.
. If a build fails a message must be sent to a group of people.

== Development Workflow - Update External Libraries
. Project with dependency decleration can be used:
.. For testing dependencies.
.. Analyzing transitiv dependencies.
.. The result of this project can be published to a local repository.

. The result from step 1 can be used in the real projects for testing.
.. The update of this configuration should be supported by special Gradle tasks.
.. It should be possible to unlock the version in a special file. So that an automatic update is feasible.

. After testing it is possible to use the same configuration for all projects.

This dependency should be stored as a special dependency in the dependency declaration of the assembly project.
If this special dependency configuration is different in the following projects with dependencies to the first project,
an error should be thrown.

== Available Plugins
There are different plugins:

https://github.com/nwillc/vplugin[com.github.nwillc.vplugin]

- Gradle plugin to report newer versions of dependencies. Traverses your compile and runtime dependencies. For each
dependency, all of your declared repositories are checked, and the highest version is found. A report is generated
showing the dependencies, their current version, and higher ones if available.

https://github.com/lkishalmi/gradle-bom-plugin[com.github.lkishalmi.bill-of-materials]

- Bill of Materials Plugin for Gradle to Manage Versions of 3rd Party Libraries in a central place.

https://github.com/spring-gradle-plugins/dependency-management-plugin[io.spring.dependency-management]

- A Gradle plugin that provides Maven-like dependency management functionality.

https://github.com/cjstehno/dependency-checker[com.stehno.gradle.dependency-checker]

- Gradle plugin for validating dependency configurations. http://cjstehno.github.io/dependency-checker.

https://github.com/ben-manes/gradle-versions-plugin[com.github.ben-manes.versions]

- In the spirit of the Maven Versions Plugin, this plugin provides a task to determine which dependencies have updates.

https://github.com/4finance/uptodate-gradle-plugin[com.ofg.uptodate]

- Gradle plugin that tells you what libs have new versions on the specified Maven repository.

https://github.com/nebula-plugins/nebula-dependency-recommender[nebula.dependency-recommender]

- Allows projects to leave off version numbers in dependencies section and have versions recommended by other sources.

https://github.com/nebula-plugins/gradle-dependency-lock-plugin[nebula.dependency-lock]

- A plugin that allows to use dynamic dependency versions to lock them to specific versions.

Unfortunately there is no single plugin that matches all requirements. There are some good ideas and implementations in these
plugins, but it is not possible to combine plugins.
